"""Initial migration

Revision ID: ac437f18c1e8
Revises: 
Create Date: 2023-06-11 19:04:16.145809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac437f18c1e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('movie_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('lang', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('releasedate', sa.DATE(), nullable=True),
    sa.Column('overview', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('poster_path', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('movie_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
